### Get Users
GET {{ja_basePath}}/orgs/Org1/users

### Get User
GET {{ja_basePath}}/orgs/Org1/users/Pierrick8

### Create User
POST {{ja_basePath}}/orgs/Org1/users

{
  "username": "Pierrick7"
}

### Delete User
DELETE {{ja_basePath}}/orgs/Org1/users/Pierrick8
